steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/pulumi-python', '.']

# Print version information.
- name: gcr.io/$PROJECT_ID/pulumi-python

images: ['gcr.io/$PROJECT_ID/pulumi-python']
tags: ['pulumi-python']